apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: ${{ secrets.DOCKER_USERNAME }}/projetdevops:database
        ports:
        - containerPort: 3306