name: Continuous Delivery

on:
  push:
    branches:
    - main
    tags:
      - '*'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker images
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/projetdevops:frontend
          docker pull ${{ secrets.DOCKER_USERNAME }}/projetdevops:backend
          docker pull ${{ secrets.DOCKER_USERNAME }}/projetdevops:database

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/

      - name: Test service URLs
        run: |
          minikube service list
          minikube service backend --url
          minikube service frontend --url
          minikube service database --url