name: Continuous integration

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main 
  
jobs:
  frontend-test: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3

    - name: Install nginx
      run: sudo apt-get install -y nginx

    - name: Start nginx
      run: sudo systemctl start nginx || sudo service nginx start

    - name: Check if nginx is running
      run: sudo systemctl is-active nginx || sudo service nginx status

    - name: Copy HTML files to nginx folder
      run: sudo cp -r index.html /usr/share/nginx/html/

    - name: List nginx HTML folder
      run: ls -l /usr/share/nginx/html/

    - name: Check nginx response
      run: curl -v http://localhost

    - name: Test frontend deployment
      run: curl --silent --fail http://localhost | grep "Pays d'Europe" || echo "Frontend not deployed correctly"
  
  backend-test: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      Db__Host: localhost
      Db__User: root
      Db__Password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      Db__Database: europe

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test || echo "No tests available for backend"